version: '3'

services:
  my_service:
    #build:
      #ockerfile: Dockerfile
    container_name: my_service
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      #- ./data-slave:/var/lib/postgresql/data-slave
      #- ./init-script:/etc/postgresql/init-script
      #- ./postgresql/.pg_service.conf:/etc/postgresql/.pg_service.conf
      #- ./postgresql/.my_pgpass:/etc/postgresql/.my_pgpass
      #- ./init.sql:/etc/postgresql/docker-entrypoint-initdb.d/init.sql #/etc/postgresql/docker-entrypoint-initdb.d/init.sql #Новая строчка кода
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=my_bd

  