# Generated by Django 5.1.5 on 2025-01-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choirister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_conductor', models.BooleanField()),
                ('description', models.TextField()),
                ('photo', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('photo', models.TextField()),
                ('has_registration', models.BooleanField()),
                ('registration_is_open', models.BooleanField(blank=True, null=True)),
                ('limit_people', models.IntegerField()),
                ('date_time_open', models.DateTimeField(blank=True, null=True)),
                ('hours_for_registration', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('text_news', models.TextField()),
                ('photo', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rehersal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('date_start', models.DateTimeField()),
                ('days_for_registration', models.IntegerField()),
                ('is_last', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('role_user', models.CharField(choices=[('Conductor', 'Conductor'), ('Admin', 'Admin')], default='Admin', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_applicant', models.JSONField()),
                ('status', models.CharField(choices=[('New', 'New Applicant'), ('Fail', 'Failed Applicant'), ('Pass', 'Passed Applicant')], default='New', max_length=4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('rehersal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.rehersal')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_visitor', models.JSONField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.event')),
            ],
        ),
    ]
