# Generated by Django 5.1.5 on 2025-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choirister',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choirister',
            name='is_conductor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_is_open',
        ),
        migrations.AddField(
            model_name='choirister',
            name='voice',
            field=models.CharField(choices=[('Первое сопрано', 'First Soprano'), ('Второе сопрано', 'Second Soprano'), ('Первый альт', 'First Alt'), ('Второй альт', 'Second Alt'), ('Первый тенор', 'First Tenor'), ('Второй тенор', 'Second Tenor'), ('Баритон', 'Baritone'), ('Бас', 'Bass')], default='Первый альт', max_length=15),
        ),
        migrations.AlterField(
            model_name='rehersal',
            name='is_last',
            field=models.BooleanField(default=True),
        ),
    ]
