# Generated by Django 5.1.5 on 2025-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_choirister_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='gallery/')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='video',
            field=models.FileField(default=None, upload_to='rehearsal/'),
        ),
        migrations.AlterField(
            model_name='choirister',
            name='photo',
            field=models.FileField(upload_to='choiristers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FileField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(upload_to='news/'),
        ),
    ]
