# Generated by Django 5.1.5 on 2025-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_photogallery_applicant_video_alter_choirister_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choirister',
            name='photo',
            field=models.FileField(upload_to='DEFAULT_FILE_STORAGE/choiristers/'),
        ),
    ]
