# Generated by Django 5.1.5 on 2025-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_choirister_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choirister',
            name='photo',
            field=models.FileField(upload_to='choir-data-bucket/'),
        ),
    ]
