# Generated by Django 5.1.5 on 2025-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_choirister_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choirister',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
