# Generated by Django 5.1.5 on 2025-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_choirister_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choirister',
            name='photo',
            field=models.FileField(upload_to='files/choiristers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FileField(upload_to='files/events/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(upload_to='files/news/'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='photo',
            field=models.FileField(upload_to='files/gallery/'),
        ),
    ]
