# Generated by Django 5.1.5 on 2025-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_choirister_photo_alter_event_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='video',
            field=models.FileField(default=None, upload_to='file/rehearsal/'),
        ),
    ]
