# Generated by Django 5.1.5 on 2025-04-25 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_applicant_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photogallery',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
