# Generated by Django 5.1.5 on 2025-04-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_photogallery_create_at_photogallery_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tmp/')),
            ],
        ),
    ]
