# Generated by Django 5.1.5 on 2025-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='files/tmp/'),
        ),
    ]
