# Generated by Django 5.1.5 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
